name: NordTech CI Foundation

# Trigga pipelinen vid push till main eller vid Pull Requests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Hämta koden
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Sätt upp Python-miljö (för unit tests, etc.)
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    # 3. Installera dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. (Definiera tester)
    - name: Run unit tests
      run: |
        pytest

    # 5. Bygg Docker Image
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag nordtech-webapp:$(date +%s)